### ISSUE TITLE
Plan for code release

### ISSUE THREAD

**Issue by lxxue** [ethanweber/nerfiller#1]
Hi Ethan,

Thank you for the great work. I wonder if you have an estimated time for code release? I really want to try it out.

**Comment by songwei100110** [comment]
Me too,it’s interesting work.

**Comment by ethanweber** [comment]
Hi @lxxue @songwei100110! I'm hoping for next week sometime. It's almost ready to ship, but I need a bit of time to remove unnecessary parts. Thanks for your patience. :)

EDIT: I'm targeting sometime before early January.

**Comment by songwei100110** [comment]
Thank you

**Comment by aiyb1314** [comment]
Thank you!

**Comment by ethanweber** [comment]
Hi, I put the code out! Let me know if things are unclear. It's a bit of steps to get it up and running (e.g., processing the data, training a Nerfacto model, and then training our model from that checkpoint, but hopefully it's clear enough). Do let me know if you have questions. While things are training, you can open up a web viewer like you normally would with Nerfstudio. This is what I did when creating camera paths, which I included a download script for.

Happy holidays and new year!
