### ISSUE TITLE
ERROR: No matching distribution found for pytorch3d

### ISSUE THREAD

**Issue by lionlai1989** [ethanweber/nerfiller#10]
Hi,
I was trying to install this package by following the description in `README.md`. Here are my steps:

### Step 1: Create virtual env
```
# Create virtual env and update packages
python3.10 -m venv venv_nerfiller \
&& source venv_nerfiller/bin/activate \
&& python3 -m pip install --upgrade pip setuptools wheel
```

### Step 2: Install nerfstuidio. Everything works perfectly.
```
# Install nerfstudio
python3 -m pip install torch==2.1.2+cu118 torchvision==0.16.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118

python3 -m pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch

python3 -m pip install nerfstudio
```

### Step 3: Install NeRFiller

```
# Install NeRFiller
pip install -e .
```

But I encountered the error:
```
INFO: pip is looking at multiple versions of nerfiller to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement pytorch3d (from nerfiller) (from versions: none)
ERROR: No matching distribution found for pytorch3d
```

I don't quite understand that since `pytorch3d` doesn't specify a version, why `pip` cannot find a version for it.

Here is my system environment:
- Python: 
```
Python: 3.10
```

- CUDA version:
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

Thank you for creating this awesome project.

**Comment by ethanweber** [comment]
Hey! First off, thanks for using my project! Could you edit the pyproject.toml on your end to remove pytorch3d, [here](https://github.com/ethanweber/nerfiller/blob/e017c6e99d379b4f488183659d7864af1f390847/pyproject.toml#L19)? Then, you could try this...

```
pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable"
```

Hopefully this helps. pytorch3d is typically tricky to install in my experience. Sometimes I clone pytorch3d locally and do whatever I can to get it running, by following [this doc](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md).

**Comment by lionlai1989** [comment]
Thanks. it works.
