### ISSUE TITLE
error when downloading blender

### ISSUE THREAD

**Issue by Orange-Ctrl** [ethanweber/nerfiller#16]
Hello! It seems the NeRF synthetic data are no longer available now.  I got a 404 error when i tried to access https://drive.google.com/uc?id=18JxhpWD-4ZmuFKLzKlAw-w5PpzZxXOcG

**Comment by ethanweber** [comment]
Hey! I just updated the repo with a new link, which you can find [here](https://github.com/ethanweber/nerfiller/blob/fad4ac133144716cad89103c8160310e3874981e/nerfiller/scripts/download.py#L40) or https://drive.google.com/uc?id=152kFJoxu5x1fblDmJhhAI6Q5XhpopUHM. Please reopen the issue if you still have a problem!
