### ISSUE TITLE
ns-launch command

### ISSUE THREAD

**Issue by aiyb1314** [ethanweber/nerfiller#2]
When I run the ns-launch command, I get a bash: ns-launch: command not found error, is it related to the version of nerfstudio?

**Comment by ethanweber** [comment]
Hey! You'll need to run pip install -e . for NeRFiller. The ns-launch command is defined in the pyproject.toml.

**Comment by ethanweber** [comment]
Did that help? You can see it defined here https://github.com/ethanweber/nerfiller/blob/c59164a0206b44b7ae8fc6b7033070a4dd558498/pyproject.toml#L47

**Comment by aiyb1314** [comment]
It's been resolved. Thank you.
