### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by BooguTeam** [ethanweber/nerfiller#3]
**Packages:**
nerfstuido : 0.3.4
pytorch-lightning: 2.1.3
torch: 2.0.1+ cu118
torchmetrics: 1.2.1
torchaudio: 2.1.2

After installation and data preparation, when I run `ns-launch train-occluder`, I still get an error (seems that **torchaudio** didn't work). So I would like to inquire about the version you used in the above Packages.
<img width="688" alt="Snipaste_2024-01-04_16-21-02" src="https://github.com/ethanweber/nerfiller/assets/33324651/412b4cdd-c852-4ada-9dda-825a0d765da1">

Thanks a lot~

**Comment by ethanweber** [comment]
Hi! Sorry for the troubles. Did you get it working? Maybe run with "--dry-run" and copy paste one command individually to start. It might be quicker to debug.

**Comment by Harr7y** [comment]
Instead of using pytorch 2.0 as required by Nerfstudio, I just used pytorch 1.8 and reinstalled the associated pakcages. Then It works. Thanks for your great work~

**Comment by ethanweber** [comment]
Okay, I'm glad you got it to work out. Thanks for working through it!
