### ISSUE TITLE
TrainingCallbackAttributes  Error

### ISSUE THREAD

**Issue by BooguTeam** [ethanweber/nerfiller#4]
When I try the ("grid-prior-du-no-depth", "none"), the error occurs. 
(I can successfully run the   ("nerfacto-nerfiller-visualize", "none") and ("nerfacto-nerfiller", "none"))

Figure 1: Error:
![image](https://github.com/ethanweber/nerfiller/assets/33324651/bc88bb26-7065-4830-9d01-cb87110487fa)

Figure 2: TrainingCallbackAttributes  in **nerfstudio**
![image](https://github.com/ethanweber/nerfiller/assets/33324651/0cc7af5f-056a-4695-b494-b73a74f475fe)

**Comment by ethanweber** [comment]
Oh yes! Can you run it with the Nerfstudio branch specified in the top of the NeRFiller README? The branch should be merged ASAP but not yet. It's quite minimal and should add the callback where it is missing.

**Comment by Harr7y** [comment]
Thanks for your reply. I manually set the trainer_base_dir to solve this problem. :no_mouth:

**Comment by Harr7y** [comment]
> Oh yes! Can you run it with the Nerfstudio branch specified in the top of the NeRFiller README? The branch should be merged ASAP but not yet. It's quite minimal and should add the callback where it is missing.

It works~  :smiley:
