### ISSUE TITLE
Occlusion of CAT

### ISSUE THREAD

**Issue by BooguTeam** [ethanweber/nerfiller#7]
I am a little confused, since the occlusion of cat is like this.
<img width="297" alt="1705727973469" src="https://github.com/ethanweber/nerfiller/assets/33324651/0d3ea435-0b82-4a71-9694-e5169c962407">

Why some images extracted from the meshes have some black blocks (some didn't have) near the carrot as follows:
<img width="528" alt="1705727935688" src="https://github.com/ethanweber/nerfiller/assets/33324651/812939ea-2c55-430e-8dc1-a36efb258989">

**Comment by ethanweber** [comment]
Hey @Harr7y, good question! So if you look at both the cat mesh and the occlusion overlaid together (for example, I use [MeshLab](https://www.meshlab.net/) or Blender to make it easy to toggle the meshes on and off), then you'll see the issue more clearly Essentially, the cylinder is taller than ideal, but if shorter, then there are other parts not covered which should be. Ideally, the 3D occluder is designed with more precision, but this is difficult in a manual way. I think finding the 3D occluder in an automated way is an interesting direction for future work.

**Comment by Harr7y** [comment]
Oh, got it~ Thanks :smiley:
